<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xs</groupId>
    <artifactId>xushu-rag-ai</artifactId>
    <version>xs-1.0</version>
    <packaging>pom</packaging>


    <properties>
        <!-- Spring AI -->
        <spring-ai.version>1.0.0</spring-ai.version>

        <!-- Spring AI Alibaba  百炼-->
        <spring-ai-alibaba.version>1.0.0.1</spring-ai-alibaba.version>
        <spring-boot.version>3.4.2</spring-boot.version>
        
        <!-- Other Dependencies Versions -->
        <lombok.version>1.18.30</lombok.version>
        <hutool.version>5.8.25</hutool.version>
        <aliyun-oss.version>3.17.4</aliyun-oss.version>
        <mybatis-plus.version>3.5.10.1</mybatis-plus.version>
        <fastjson2.version>2.0.43</fastjson2.version>
        <jjwt.version>0.9.1</jjwt.version>
        <pagehelper.version>1.4.7</pagehelper.version>
        <ik-analyzer.version>8.5.0</ik-analyzer.version>
        <mysql-connector.version>8.0.33</mysql-connector.version>
        <druid.version>1.2.20</druid.version>

    </properties>

    <modules>
        <module>xushu-rag-ai-back</module>
        <module>SuperSQL</module>
    </modules>


    <dependencyManagement>
        <dependencies>
            <!-- Spring Boot -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            
            <!-- Spring AI -->
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-bom</artifactId>
                <version>${spring-ai.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            
            <!-- Spring AI Alibaba -->
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-starter</artifactId>
                <version>${spring-ai-alibaba.version}</version>
            </dependency>
            
            <!-- Other Dependencies -->
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.aliyun.oss</groupId>
                <artifactId>aliyun-sdk-oss</artifactId>
                <version>${aliyun-oss.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.fastjson2</groupId>
                <artifactId>fastjson2</artifactId>
                <version>${fastjson2.version}</version>
            </dependency>

            <dependency>
                <groupId>io.jsonwebtoken</groupId>
                <artifactId>jjwt</artifactId>
                <version>${jjwt.version}</version>
            </dependency>

            
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>${pagehelper.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.github.magese</groupId>
                <artifactId>ik-analyzer</artifactId>
                <version>${ik-analyzer.version}</version>
            </dependency>
            
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>${mysql-connector.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            
            <!-- Spring AI Modules -->
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-tika-document-reader</artifactId>
                <exclusions>
                    <exclusion>
                        <groupId>org.apache.pdfbox</groupId>
                        <artifactId>pdfbox</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>org.apache.pdfbox</groupId>
                <artifactId>pdfbox</artifactId>
                <version>3.0.4</version>
            </dependency>
            
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-autoconfigure-model-chat-memory</artifactId>
                <version>${spring-ai.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-pdf-document-reader</artifactId>
                <version>${spring-ai.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-advisors-vector-store</artifactId>
                <version>${spring-ai.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.springframework.ai</groupId>
                <artifactId>spring-ai-starter-vector-store-milvus</artifactId>
                <version>${spring-ai.version}</version>
            </dependency>
            
            <!-- Spring AI Alibaba Modules -->
            <dependency>
                <groupId>com.alibaba.cloud.ai</groupId>
                <artifactId>spring-ai-alibaba-starter-dashscope</artifactId>
                <version>${spring-ai-alibaba.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>


    <repositories>
        <repository>
            <id>aliyunmaven</id>
            <name>aliyun</name>
            <url>https://maven.aliyun.com/repository/public</url>
        </repository>
    </repositories>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>17</source>
                    <target>17</target>
                    <encoding>UTF-8</encoding>
                    <parameters>true</parameters>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
